// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzM7QeUgrGaKOKRRafz8pK_wTFxVasAdQ',
    appId: '1:843150720638:web:c0bff34a2154593950622f',
    messagingSenderId: '843150720638',
    projectId: 'iottuoitieuthongminh-22b34',
    authDomain: 'iottuoitieuthongminh-22b34.firebaseapp.com',
    databaseURL: 'https://iottuoitieuthongminh-22b34-default-rtdb.firebaseio.com',
    storageBucket: 'iottuoitieuthongminh-22b34.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6aD2dc9ZCMJRV2-xdMXEuXGbsCL1-rIY',
    appId: '1:843150720638:android:7e6571201de7312550622f',
    messagingSenderId: '843150720638',
    projectId: 'iottuoitieuthongminh-22b34',
    databaseURL: 'https://iottuoitieuthongminh-22b34-default-rtdb.firebaseio.com',
    storageBucket: 'iottuoitieuthongminh-22b34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHJbEgWRO7C7gDN-l-uToD4Wr5vOtJkcQ',
    appId: '1:843150720638:ios:06f01c05ecf5412450622f',
    messagingSenderId: '843150720638',
    projectId: 'iottuoitieuthongminh-22b34',
    databaseURL: 'https://iottuoitieuthongminh-22b34-default-rtdb.firebaseio.com',
    storageBucket: 'iottuoitieuthongminh-22b34.firebasestorage.app',
    iosBundleId: 'com.example.tuoitieuthongminh',
  );
}
